version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: place_choose_app
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www/html
        depends_on:
            - db

    db:
        image: postgres:13
        container_name: place_choose_db
        environment:
            POSTGRES_DB: place_choose
            POSTGRES_USER: place_choose
            POSTGRES_PASSWORD: place_choose
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
